package analyser

enum class Symbol(val value: String, val code: Int) {
    PROGRAMA(value = "PROGRAMA", code = 1),
    DECLARACOES(value = "DECLARACOES", code = 2),
    FIM_DECLARACOES(value = "FIM-DECLARACOES", code = 3),
    FUNCOES(value = "FUNCOES", code = 4),
    FIM_FUNCOES(value = "FIM-FUNCOES", code = 5),
    FIM_PROGRAMA(value = "FIM-PROGRAMA", code = 6),
    TIPO_VAR(value = "TIPO-VAR", code = 7),
    VAZIO(value = "VAZIO", code = 8),
    REAL(value = "REAL", code = 9),
    INTEIRO(value = "INTEIRO", code = 10),
    CADEIA(value = "CADEIA", code = 11),
    LOGICO(value = "LOGICO", code = 12),
    CARACTER(value = "CARACTER", code = 13),
    TIPO_FUNC(value = "TIPO-FUNC", code = 14),
    FIM_FUNC(value = "FIM-FUNC", code = 15),
    TIPO_PARAM(value = "TIPO-PARAM", code = 16),
    SE(value = "SE", code = 17),
    FIM_SE(value = "FIM-SE", code = 18),
    SENAO(value = "SENAI", code = 19),
    ENQUANTO(value = "ENQUANTO", code = 20),
    FIM_ENQUANTO(value = "FIM-ENQUANTO", code = 21),
    RETORNA(value = "RETORNA", code = 22),
    PAUSA(value = "PAUSA", code = 23),
    IMPRIME(value = "IMPRIME", code = 24),
    TRUE(value = "TRUE", code = 25),
    FALSO(value = "FALSO", code = 26),

    PONTO_E_VIRGULA(value = ";", code = 101),
    COLCHETES_ABRIR(value = "[", code = 102),
    COLCHETES_FECHAR(value = "]", code = 103),
    DOIS_PONTOS(value = ":", code = 104),
    VIRGULA(value = ",", code = 105),
    PARENTESES_ABRIR(value = "(", code = 106),
    PARENTESES_FECHAR(value = ")", code = 107),
    INTERROGACAO(value = "?", code = 108),
    CHAVES_ABRIR(value = "{", code = 109),
    CHAVES_FECHAR(value = "}", code = 110),
    MENOR_OU_IGUAL(value = "<=", code = 111),
    MENOR(value = "<", code = 112),
    MAIOR(value = ">", code = 113),
    MAIOR_OU_IGUAL(value = ">=", code = 114),
    IGUAL(value = "==", code = 115),
    DIFERENTE(value = "!=", code = 116),
    HASHTAG(value = "#", code = 116),
    SOMA(value = "+", code = 117),
    SUBTRACAO(value = "-", code = 118),
    MULTIPLICACAO(value = "*", code = 129),
    DIVISAO(value = "/", code = 120),
    SOBRA_DIVISAO(value = "-", code = 121),
    ATRIBUICAO(value = ":=", code = 122),

    NOM_PROGRAMA(value = "NOM-PROGRAMA", code = 201),
    VARIAVEL(value = "VARIAVEL", code = 202),
    NOM_FUNCAO(value = "NOM-FUNCAO", code = 203),
    CONS_INTEIRO(value = "CONS-INTEIRO", code = 204),
    CONS_REAL(value = "CONS-REAL", code = 205),
    CONS_CADEIA(value = "CONS-CADEIA", code = 206),
    CONS_CARACTER(value = "CONS-CARACTER", code = 207),
}