package core

enum class Atomo(val valor: String, val code: Int) {
    PROGRAMA(valor = "PROGRAMA", code = 1),
    DECLARACOES(valor = "DECLARACOES", code = 2),
    FIM_DECLARACOES(valor = "FIM-DECLARACOES", code = 3),
    FUNCOES(valor = "FUNCOES", code = 4),
    FIM_FUNCOES(valor = "FIM-FUNCOES", code = 5),
    FIM_PROGRAMA(valor = "FIM-PROGRAMA", code = 6),
    TIPO_VAR(valor = "TIPO-VAR", code = 7),
    VAZIO(valor = "VAZIO", code = 8),
    REAL(valor = "REAL", code = 9),
    INTEIRO(valor = "INTEIRO", code = 10),
    CADEIA(valor = "CADEIA", code = 11),
    LOGICO(valor = "LOGICO", code = 12),
    CARACTER(valor = "CARACTER", code = 13),
    TIPO_FUNC(valor = "TIPO-FUNC", code = 14),
    FIM_FUNC(valor = "FIM-FUNC", code = 15),
    TIPO_PARAM(valor = "TIPO-PARAM", code = 16),
    SE(valor = "SE", code = 17),
    FIM_SE(valor = "FIM-SE", code = 17),
    SENAO(valor = "SENAI", code = 18),
    ENQUANTO(valor = "ENQUANTO", code = 19),
    FIM_ENQUANTO(valor = "FIM-ENQUANTO", code = 20),
    RETORNA(valor = "RETORNA", code = 21),
    PAUSA(valor = "PAUSA", code = 22),
    IMPRIME(valor = "IMPRIME", code = 23),
    TRUE(valor = "TRUE", code = 24),
    FALSO(valor = "FALSO", code = 25),

    PONTO_E_VIRGULA(valor = ";", code = 101),
    COLCHETES_ABRIR(valor = "[", code = 102),
    COLCHETES_FECHAR(valor = "]", code = 103),
    DOIS_PONTOS(valor = ":", code = 104),
    VIRGULA(valor = ",", code = 105),
    PARENTESES_ABRIR(valor = "(", code = 106),
    PARENTESES_FECHAR(valor = ")", code = 107),
    INTERROGACAO(valor = "?", code = 108),
    CHAVES_ABRIR(valor = "{", code = 109),
    CHAVES_FECHAR(valor = "}", code = 110),
    MENOR_OU_IGUAL(valor = "<=", code = 111),
    MENOR(valor = "<", code = 112),
    MAIOR(valor = ">", code = 113),
    MAIOR_OU_IGUAL(valor = ">=", code = 114),
    IGUAL(valor = "==", code = 115),
    DIFERENTE(valor = "!=", code = 116),
    HASHTAG(valor = "}", code = 117),
    SOMA(valor = "+", code = 118),
    SUBTRACAO(valor = "-", code = 119),
    MULTIPLICACAO(valor = "*", code = 120),
    DIVISAO(valor = "/", code = 121),
    SOBRA_DIVISAO(valor = "-", code = 122),
    ATRIBUICAO(valor = ":=", code = 123),

    NOM_PROGRAMA(valor = "NOM-PROGRAMA", code = 201),
    VARIAVEL(valor = "VARIAVEL", code = 202),
    NOM_FUNCAO(valor = "NOM-FUNCAO", code = 203),
    CONS_INTEIRO(valor = "CONS-INTEIRO", code = 204),
    CONS_REAL(valor = "CONS-REAL", code = 205),
    CONS_CADEIA(valor = "CONS-CADEIA", code = 206),
    CONS_CARACTER(valor = "CONS-CARACTER", code = 207),
}